import turtle
ttl=turtle.Turtle()
ttl.pensize(5)
ttl.color('orange','orange')
ttl.begin_fill()
ttl.forward(500)
ttl.penup()
ttl.left(90)
ttl.pendown()
ttl.forward(100)
ttl.penup()
ttl.left(90)
ttl.pendown()
ttl.forward(500)
ttl.penup()
ttl.left(90)
ttl.pendown()
ttl.forward(100)
ttl.end_fill()


ttl.penup()
ttl.color('green','green')
ttl.begin_fill()
ttl.forward(100)
ttl.left(90)
ttl.pendown()
ttl.forward(500)
ttl.right(90)
ttl.forward(100)
ttl.left(-90)
ttl.forward(500)
ttl.left(-90)
ttl.forward(100)
ttl.end_fill()

ttl.penup()
ttl.pensize(4)
ttl.color('blue')
ttl.setpos(300,-50)
ttl.pendown()
ttl.circle(50)
ttl.penup()
ttl.pensize(2)
ttl.setpos(250,-50)
ttl.pendown()
for i in range(24):
    ttl.backward(50)
    ttl.forward(50)
    ttl.left(15)

ttl.penup()
ttl.hideturtle()
ttl.color('orange')
ttl.setpos(-500,80)
ttl.pendown()
ttl.write("Happy",font=("verdana",60,"normal"))

ttl.penup()
ttl.color('blue')
ttl.setpos(-500,-80)
ttl.pendown()
ttl.write("REPUBLIC",font=("verdana",70,"normal"))

ttl.penup()
ttl.color('green')
ttl.setpos(-500,-200)
ttl.pendown()
ttl.write("DAY",font=("verdana",60,"normal"))
turtle.done()