str="master"
str1="Mind"
str2="PERSON"
print(str.islower())
print(str1.islower())
print(str2.islower())
print(str.isupper())
print(str1.isupper())
print(str2.isupper())
print(str.istitle())
print(str1.istitle())
print(str2.istitle())